# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    mink:
                        # Pass: mink123
                        password: $2y$12$O00G9Gwk/lZFHpYSSC1uKuB/nsUxrrNVVJitydwj7IOf2dKo9RZZm
                        roles: 'ROLE_USER'
                    admin:
                        # Pass: admin123
                        password: $2y$12$nOadYn9.4Py.AkTGbE0Bs.gMzlbbEsX4G8uWz8kEjaoaJjEkJVCXS
                        roles: 'ROLE_ADMIN'
    
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: login
                check_path: login
            
            logout:
                path:   /logout
                target: /
                
    access_control:
        - { path: ^/secure, roles: [ROLE_USER,ROLE_ADMIN] }
        - { path: ^/insecure, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/login, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
      
        